### ISSUE TITLE
Opportunity Controller with User Sessions. Things that need to be added and considered.

### ISSUE THREAD

**Issue by toscanowilliam** [digitaljosh/payitforward#38]
1. User cannot claim or complete own opportunity.

2. User can only edit, or delete his own opportunities

3.  If a User claims or completes an oppportunity, it should show up on their profile as “claimed” and “completed” opportunities.

4.  If a user claims and completed and opportunity, it shoud only show up as “claimed” or “Completed” according to the specific user who’s logged in. 
        This is an issue because if one user changes the boolean value “claimed”,
        to true, now other users can’t claim it. I think I need to create a duplicate of that opportunity that was just claimed, and save it under the user_id as a claimed opportunity.
    So in the User model, there should be a getter and setter for “claimedOpportunity” and “CompletedOpportunity”. And those opportunities can show up in the user profile.

**Comment by dpryor67** [comment]
#1 and 2 are completed - users can only edit and remove opportunities they created, and they can't claim or complete their own.

**Comment by dpryor67** [comment]
#4 is functional too - the claimed and completed are linked to the specific users.

**Comment by dpryor67** [comment]
#3 is completed - just has to be merged.
