### ISSUE TITLE
Add sessions to opportunity/edit and opportunity/remove

### ISSUE THREAD

**Issue by rubyarbogast** [digitaljosh/payitforward#85]
Right now, anyone can edit or remove an opportunity. We need to add session attributes to make sure only the creating user can do so.

**Comment by rubyarbogast** [comment]
Also could someone please take out the cheese comments from /remove? I'll do so if I end up doing the session stuff.

**Comment by dpryor67** [comment]
The code in my pull request will fix this issue by checking if the current user is the same as the creating user by comparing usernames. I also took out the cheese comments, though I can't imagine why you didn't want to keep them :)
